### ISSUE TITLE
Check TMDB API configuration

### ISSUE THREAD

**Issue by sebtouze** [macaw-movies/macaw-movies#101]
I think we should try and check the TMDB API config on app startup. This is true for posters bur not only. See: http://docs.themoviedb.apiary.io/#reference/configuration/configuration
First step will be to check the poster URL. 

We must also find a way to check if the keywords do not change in the API config.

**Comment by ochurlaud** [comment]
can you do this at fetchmetadataQuery startup? The urls and interessant keywords can be added in new attributes of the class.
