### ISSUE TITLE
[MetadataDialog] bug when clicking twice on search button

### ISSUE THREAD

**Issue by ochurlaud** [macaw-movies/macaw-movies#105]
It calls FetchMetadataQuery::sendPrimaryRequest() twice, causing a problem in the signal/slot management. FetchMetadataQuery should be only activated when not active. (idem for other query)

**Comment by sebtouze** [comment]
I suppose we need to check somehow if the sendPrimaryRequest function has already been called. 
So an easy way could be to have a `bool m_isPrimaryRequestSent` set to `true` at the fisrt call then set again to `false` when `on_primaryRequestResponse` is called. 
Is this what you want to do ?

**Comment by ochurlaud** [comment]
I think we could have a token in `FetchMetadataQuery` that follows the queries of each `QNetworkAccessManager`:

For instance a `QList<QString>` that contains:

    "primary"
    "movie"
    "people"

The reason of this is that it would trace the whole process (if i get the same problem with the movie query later, we can easily solve it, without adding another boolean attribute).

Do you think it's a good idea? or overkill?

**Comment by ochurlaud** [comment]
I wanted to do a simple test "isSignalConnected" but it is said to break the Object Orinted principle....

http://doc.qt.io/qt-5/qobject.html#isSignalConnected

**Comment by ochurlaud** [comment]
other idea: do this:

    if (m_networkManager->receivers(SIGNAL(finished(QNetworkReply*))) == 0) {
         do whatever....
    }
