### ISSUE TITLE
Refreshing screen when quitting tags page

### ISSUE THREAD

**Issue by sebtouze** [macaw-movies/macaw-movies#108]
When clicking on "Tags" button the view change to show the tag list on the left and the corresponding movies in the central view. 
But when clicking again on "Tags" to exit this view we stay on it until force refreshing choosing for example to select "Directors" in the combo-box. 
An emit refresh mush be added

**Comment by ochurlaud** [comment]
this is not a bug...

It was the attended behaviour. The question is: do people understand this?

**Comment by sebtouze** [comment]
Well I did not. Why should it work this way?

**Comment by sebtouze** [comment]
OK, as disused on IRC, let's move "Tag" button on the combo box listing Actors, Directors and Producers
