### ISSUE TITLE
Managing series

### ISSUE THREAD

**Issue by ochurlaud** [macaw-movies/macaw-movies#110]
It will be no picnic :)

But let's think about it!

**Comment by ochurlaud** [comment]
Add boolean "Series" and a link Serie-Season-episode then think about how to display.... Maybe 3 columns?

+ api query...

**Comment by sebtouze** [comment]
Concerning the db, 3 columns should be enough right: 
1. id_serie => null if not part of a serie
2. serie_season
3. serie_episode

There is another point about series, is how we display episodes in the interface: series' episodes are not individuals movies. Maybe put a sort of tree-list ?

**Comment by ochurlaud** [comment]
For the API: http://docs.themoviedb.apiary.io/#reference/tv

Now a question: Do we use a QTreeWidget or a QColumnView?

@sebtouze  ↑

**Comment by sebtouze** [comment]
I have a personal preference for QTreeWidgets. 
It could also be interesting to think of a different view: a solution would be to only put one line for the whole series and then on click let access a view dedicated to this serial episodes.

**Comment by ochurlaud** [comment]
@sebtouze: alright for your database scheme, i like it. What about the object Movie?

```
Movie {
int m_id
...
bool m_isSeries
Series m_series;
int m_seriesSeason;
int m_seriesEpisode;
}
```

* or create a struct series which contains the object Series, the 2 ints?
* or create a class that links a movie to series object and affects the 2 ints?

**Comment by sebtouze** [comment]
I think the last one is the best. And yes `Series` should be something very simple like: 
```
Series 
{
QString m_name
QList<int> m_seasons //list of number of episodes for each season, Series have m_seasons.size() seasons
bool m_finished; // series finished of not
QList<Movies*>
}
```

**Comment by ochurlaud** [comment]
closed with a3904c4a77fde8862d0d397afce7277ec6fdba42

**Comment by ochurlaud** [comment]
Slowly coming

**Comment by ochurlaud** [comment]
Everything on this topic is done. If needed, we'll open a new one.
