### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by kopiersperre** [macaw-movies/macaw-movies#111]
I've compiled from AUR (https://aur.archlinux.org/packages/macaw-movies-git/). I'm using qt5-base 5.4.1

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6fdfbac in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5

**Comment by ochurlaud** [comment]
But where you able to launch it?

Please launch it from a terminal with option --debug and please send the trace here... 

Thx for your feedback

**Comment by kopiersperre** [comment]
I used gdb. Without I don't get more than "Segmentation fault (core dumped)"

**Comment by ochurlaud** [comment]
So you get the seg fault before anything happens? else, please see if gdb or the --debug option give you some more info: I installed it too (I'm also on Arch) and everything works fine....

**Comment by kopiersperre** [comment]
does not occur anymore

**Comment by ochurlaud** [comment]
Then I close it. Thx for reporting !
