### ISSUE TITLE
Movie Poster is Cropped in Meta Data Panel

### ISSUE THREAD

**Issue by jrutanen** [macaw-movies/macaw-movies#124]
The movie poster is cropped from the bottom and from the top unless the metadata panel is very wide or narrow. See picture below as an example. OS is Mac OS X Yosemite

![nofullmovieposter](https://cloud.githubusercontent.com/assets/5951883/8016151/06a2d3a6-0be0-11e5-9f9e-cb23ea32dc0f.png)

**Comment by ochurlaud** [comment]
It's not the case on my version... can you confirm? For all posters? 

Try to play around [this line](https://github.com/macaw-movies/macaw-movies/blob/master/src/MainWindowWidgets/MetadataPannel.cpp#L70) to see if something is changing.  Maybe Qt has a problem with MacOSX (but it would be weird)

**Comment by ochurlaud** [comment]
@jrutanen Does it happen when you change the size of the window and only then? If yes, we were aware of the issue, but didn't have time to correct it.

**Comment by jrutanen** [comment]
I noticed than when the metadata panel is narrow everything looks good. Clipping happens because the picture size is related to the metapannel size (this->...). If the panel is fairly narrow everything works well, but if you draw the panel a bit wider the picture becomes too high and is clipped since the poster label can't have all the space that is needed for the picture. So amount of clipping is related to the length of the description and amount of other information (director, actors) about the film.

Same is also seen for the text labels. When the space is not enough the text in the top label is not fully shown (see picture below). Solution could be to have scrollable widget or have a "more..." button. I'll experiment a little to find alternative solution.

![labeloverlap](https://cloud.githubusercontent.com/assets/5951883/8042276/72898660-0e1e-11e5-9a13-5bcbf4006f96.png)

**Comment by jrutanen** [comment]
I noticed the when doing the resize everything is not working perfectly, but in this case the issue is seen when new movie is selected from the movie pannel even when window is not resized.

**Comment by ochurlaud** [comment]
@jrutanen  last commit (8039975cd61a66c4d39ba42b8eb5da1a26292907) corrected the text problem. The picture is not supposed to create problem, the way it's currently handled: it's the last thing done, and it's based on the place available. Please check the master.

**Comment by ochurlaud** [comment]
However we still have a problem about the sizes in this pannel. I open an new issue for that

**Comment by ochurlaud** [comment]
@jrutanen I think it's alright now. If so, please close the issue.
Thx

**Comment by jrutanen** [comment]
The problem is gone. I think it would look better if the director/actor information and description is inside one label with one scrollbar, but I guess that is a matter or opinion. Reported issue is gone so I close the ticket.

**Comment by ochurlaud** [comment]
@jrutanen  You may be right... 

@sebtouze what do you think?

**Comment by sebtouze** [comment]
For me the way it is done is OK, one label for people and one for description
