### ISSUE TITLE
Row spacing in the left pannel is not correct when width is very low

### ISSUE THREAD

**Issue by jrutanen** [macaw-movies/macaw-movies#126]
After changing the width of the left pannel the row spacing for the names/tags becomes uneven. Some are ok, some are not, seems to be based on if tag name needs to be divided into two rows or not.

![strangelinespacing](https://cloud.githubusercontent.com/assets/5951883/8020288/981d83ce-0c73-11e5-9a0a-e839a23471e9.png)

**Comment by ochurlaud** [comment]
I may have checked wordwrap here. I'll check that.
