### ISSUE TITLE
Upgrade DB: only when releases!

### ISSUE THREAD

**Issue by ochurlaud** [macaw-movies/macaw-movies#131]
The upgradeDB should only exist between release.

So the CREATE TABLE media_player  should just disappear. We are in dev, we can have not-so-good ideas, and change afterwards our minds, without having to keep a trace of this in the production code.

So if something happens again, just say it on the mailing list, and change the current update

**Comment by ochurlaud** [comment]
https://mail.kde.org/pipermail/macaw-movies/2015-July/000009.html

**Comment by sebtouze** [comment]
We surely can delete the content of the upgrad tool if you want. 
Put this info in the read me to be sure everybody reads it.

**Comment by ochurlaud** [comment]
@sebtouze Already deleted. I added a comment... I'll update the readme later.
