### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by ochurlaud** [macaw-movies/macaw-movies#54]
Create menus to 

* look for all metadata, metadata of selected movies,
* set options (do we want to fetch metadata? Do you want to display this ? ....)
* Choose default media player
* ....

**Comment by ochurlaud** [comment]
@Nanoseb: you could do this I think.

The settings window should have several tabs and we should choose if the user wants to get the metadata, reimport all folders,..)

Something cool would be to decide here which  headers the mainWindow shows (ping me on IRC for this).

**Comment by jrutanen** [comment]
Menu field to Choose default media player would also be nice.

**Comment by ochurlaud** [comment]
jrutanen: you're right.  We'll think about this for the next release.

**Comment by jrutanen** [comment]
I've made a prototype for extended settings menu with possibility to select media player. Please see the pictures below for review.

Following changes were needed:
1. New media player table in the database
2. New functions to databaseManager to set and get media player path
3. new process to start external media player in case user doesn't want to use the system default player
    - I'm working on mac so the functionality for mac has been tested. I've not tested if the code below actually works on Linux or Windows yet. If someone can check the other platforms that would be great.

Fork with the changes: https://github.com/jrutanen/macaw-movies

    if (!databaseManager->getMediaPlayerPath().compare("")) {
        QString l_executeMediaPlayerPath;
        #ifdef Q_OS_LINUX
            l_executeMediaPlayerPath(QString("source \"%1\"").arg(databaseManager->getMediaPlayerPath()));
        #endif
        #ifdef Q_OS_WIN
            l_executeMediaPlayerPath = QString("\"%1\"").arg(databaseManager->getMediaPlayerPath());
        #endif
        #ifdef Q_OS_OSX
            l_executeMediaPlayerPath = QString("open %1").arg(databaseManager->getMediaPlayerPath());
        #endif

        QProcess::startDetached(QString("%1 \"%2\"")
                                       .arg(l_executeMediaPlayerPath)
                                       .arg(l_movie.filePath()));
    } else {
        QDesktopServices::openUrl(QUrl("file://" + l_movie.filePath(), QUrl::TolerantMode));
    }

![settingswindow](https://cloud.githubusercontent.com/assets/5951883/8008178/c513a738-0ba0-11e5-863d-5e5886135e55.png)
![settingswindowpreferences](https://cloud.githubusercontent.com/assets/5951883/8008185/cdae2f94-0ba0-11e5-9bc9-e101730b7552.png)
![settingswindowpreferences2](https://cloud.githubusercontent.com/assets/5951883/8008188/cff86f30-0ba0-11e5-9c02-f3e73fe86bda.png)

**Comment by ochurlaud** [comment]
just tried to compile your master branch.. doesn't compile with cmake... 

```
src/MainWindowWidgets/MoviesPannel.cpp:246:105: erreur: no match for call to ‘(QString) (QString)’
             l_executeMediaPlayerPath(QString("source \"%1\"").arg(databaseManager->getMediaPlayerPath()));
```

**Comment by ochurlaud** [comment]
Tested under Linux: 
 *The bug above was corrected on mac/windows: use `l_executeMediaPlayerPath = ...`
 * the filters for applications on linux are.. *nothing*: we use vlc, mplayer... without extensions.
 * The table name is not the same in the database and in the function used in DatabaseManager

**Comment by ochurlaud** [comment]
I think it's a cool improvement

@sebtouze  IMO the path of the media player should be in the `config` table what do you think?

**Comment by ochurlaud** [comment]
@jrutanen  Please do a pull-request when you think its ok.

**Comment by sebtouze** [comment]
I don't know if you still expect any answer from me...
I agree it shoul be in the config db. To be changed. 
I will do
