### ISSUE TITLE
Set a fix size for the right pannel

### ISSUE THREAD

**Issue by sebtouze** [macaw-movies/macaw-movies#58]
Hi

the right panel displaying all the information about selected move have different size according to the film's title.

I think it would be better to fix this panel size.

**Comment by sebtouze** [comment]
Well it's not done, I reopen

**Comment by ochurlaud** [comment]
duplicate #75

**Comment by ochurlaud** [comment]
e461be4bb51051158ef0055e92fe39aedb123e81 fix this in the same time as #75
