### ISSUE TITLE
Workflow change for People/Tags

### ISSUE THREAD

**Issue by ochurlaud** [macaw-movies/macaw-movies#72]
* When people/tag is added, save it directly in the DB. 

* If then the modification of the movies' metadata is canceled popup "do you want to keep the actors ?"

* When a movie is deleted, ask for each actor that is not linked anymore to a movie a popup "XXX is not in any movie, do you want to keep it ?"

**Comment by ochurlaud** [comment]
I think it's a good middle ground between what is currently implemented and the problems that you said @sebtouze

**Comment by sebtouze** [comment]
Yep, agreed. 
Not sure it's a major addition though
