### ISSUE TITLE
Add SQL foreign key constrains

### ISSUE THREAD

**Issue by sebtouze** [macaw-movies/macaw-movies#77]
Hi, 

Looking at the *DatabaseManager::deleteMovie*, I think it could be useful to a **ON DELETE CASCADE** constrain on *movies_tag* and *movies_people* foreign keys to make the deletion of a movie easier.

**Comment by ochurlaud** [comment]
@sebtouze I don't know if SQLite can do it... I've never used this feature.

Try and report =D

**Comment by ochurlaud** [comment]
@sebtouze  http://stackoverflow.com/questions/5890250/on-delete-cascade-in-sqlite3
