### ISSUE TITLE
Improve tags' design implemetation

### ISSUE THREAD

**Issue by sebtouze** [macaw-movies/macaw-movies#78]
Hi, 

The current way to select the tags is OK but I think a list of check-boxes will be better and easier to use for the user. 

Also we can add an add/remove tag button inside the MainWindow. 

All those points are to discuss.

**Comment by ochurlaud** [comment]
@sebtouze We discussed it on skype. Check boxes would be better or like the people widget. You can choose what is more relevant for you...
