### ISSUE TITLE
Save movie posters

### ISSUE THREAD

**Issue by ochurlaud** [macaw-movies/macaw-movies#84]
Do we save the posters in the database as blob or do we save a path in the database (like `normal_folder/id.jpg` where `normal_folder` is defined in Application)?

**Comment by ochurlaud** [comment]
We said folder. For linux `.local/share/macaw-movies/posters/{id}.jpg`

If sebtouze you could implement this...

**Comment by ochurlaud** [comment]
@sebtouze I prepared everything in the database and the entities, you just have to define the good folder (in `./local/share.... ` etc... ) and update the MetadataQuery.

It's a good way to understand how I implemented this.

**Comment by sebtouze** [comment]
Do you think it is useful to have the poster's path in the db if we use the standard <path to MM config fils>/poster/<id>.jpg ?

**Comment by ochurlaud** [comment]
Nope. you can keep only the id.
