### ISSUE TITLE
Show to the user the number of movies imported

### ISSUE THREAD

**Issue by sebtouze** [macaw-movies/macaw-movies#85]
It can be interesting for the user to know how many movies have just been imported after validation of the settings window. 
Just adding a messageBox should be enought

**Comment by ochurlaud** [comment]
maybe a progress bar in the status pannel (completely at the bottom of the window) could be good.

A message Box is too intrusive (I mean that I don't care of this number) but in the status bar it's a good idea.

**Comment by ochurlaud** [comment]
currently, each time a movie is imported, `Application` receives a signal. This signal should be used to update the status pannel (and using a count: `nb_imported/nb_toImport`)

**Comment by ochurlaud** [comment]
@Nanoseb you can do that if you want.

Create a basic widget that has a progress bar that progress each time the signal updatedMovie() is sent. It could then get the size of the list of movies remaining in the queue or something like this.

We will then attach the widget to the mainwindow.

**Be careful:** during the process of fetching the queue list decrease when it's imported, but grows if Application asks to get fetch more Movies!

**Comment by sebtouze** [comment]
first step in 4e9a7a38a882e60305b0785e76c46e879a40864e

**Comment by sebtouze** [comment]
Closed with 920d799a03c357adea00465d6fd5afab976ffbd0
