### ISSUE TITLE
MetadataDialog is to often shown

### ISSUE THREAD

**Issue by ochurlaud** [macaw-movies/macaw-movies#89]
The algorithm to fetch the data should be optimized.

**Comment by sebtouze** [comment]
I suppose you meant FetchMetadataDialog ?

**Comment by ochurlaud** [comment]
no I meant in FetchMetadata(Query?) we should have better algorithm.

**Comment by sebtouze** [comment]
Well I was talking about the title in my last message. 
Can we just add a "stop asking" button for all movies imported from the same directory ? What's your opinion ?

**Comment by ochurlaud** [comment]
Agreed abut maybe in another milestone then because it also needs menus to look for the metadata again and so on
