### ISSUE TITLE
MainWindow should be repainted after each new importation

### ISSUE THREAD

**Issue by ochurlaud** [macaw-movies/macaw-movies#90]
When a film is imported/modified the window should be repainted

**Comment by sebtouze** [comment]
Well not quite sure if it's useful to repaint on each individual film importation: after a whole directory should be enough ? 

As I see it, this is a more generic issue: we do not refresh often enough the list, e.g. when switching between actor/director/producers/tags/... the main panel is not always refreshed as it would.

**Comment by ochurlaud** [comment]
I would say every 10 movies...
