### ISSUE TITLE
Problem with the To Watch list when selecting Actors/Directors/Producer

### ISSUE THREAD

**Issue by sebtouze** [macaw-movies/macaw-movies#91]
I think the title is quite explicit : when in the To Watch view (button "To Watch" checked), selecting a director (or other person type), The view shows all the movies. 
It must show only this person movies witch are in the "To Watch" playlist.

**Comment by ochurlaud** [comment]
Doing this is possible only if we remove all the black magic behind those functions:

* MainWindow::void fillMainPannel()
* MainWindow::void fillLeftPannel(int typeElement, int typePeople)
* MainWindow::void prepareMoviesToDisplay(int id)
* MainWindow::filterPannels()

So it's quite difficult

**Comment by ochurlaud** [comment]
I looked to the code... I know how to simplify it.. I'll try to do it next week

**Comment by ochurlaud** [comment]
cd #97
