### ISSUE TITLE
Unused code on "on_customContextMenuRequested"  ? 

### ISSUE THREAD

**Issue by sebtouze** [macaw-movies/macaw-movies#92]
In MainWindow::on_customContextMenuRequested, I'm not quite sure to see the use for the Qmenu object l_addPlaylistMenu as its only action is linked to the contextual menu (l_menu).

**Comment by ochurlaud** [comment]
It's a "leftover" from when the playlists were implemented.

It's a way to already have the code design for playlists.

**Comment by sebtouze** [comment]
Well, I'm not quite sure it's a good idea to keep old code. This may be forgotten later on. 
I think we can delete this, it's not much to make it back if needed.

**Comment by ochurlaud** [comment]
then remove it and close the issue
