### ISSUE TITLE
Movie deletion

### ISSUE THREAD

**Issue by ochurlaud** [macaw-movies/macaw-movies#93]
* f0189426dc68d43ab83ae75c2b4c04c40a40f7dd should move to trash and not permanently delete
* a QMessageBox should ask for confirmation.

**Comment by sebtouze** [comment]
There is already a QMsgBog ;)
I agree for the move-to-trash thing.

**Comment by ochurlaud** [comment]
http://stackoverflow.com/questions/17964439/move-files-to-trash-recycle-bin-in-qt

It's not easy... I change this

**Comment by sebtouze** [comment]
Well, I think I've been a bit toot fast. 
The way things are done do not work the way it should be for a file located in a volume other than /home (for GNU/Linux and Mac OSX)

**Comment by ochurlaud** [comment]
@sebtouze  You should write somewhere where you took the sources of the code for mac/windows and so on.  It doesn't look trivial at all and I'm not the one who will maintain this part because... I don't understand it well

**Comment by ochurlaud** [comment]
http://www.ramendik.ru/docs/trashspec.html

**Comment by sebtouze** [comment]
Right, I put some more doc in this code. 
For now I close this issue as it is solved since eeacd5eb2872f67f759a4cfc2005aa6dc71aaa8a
