### ISSUE TITLE
App failure when removing a movie from 'ToWatch' playlist

### ISSUE THREAD

**Issue by sebtouze** [macaw-movies/macaw-movies#99]
I've got a bug, *sometimes*, when removing a movie from the to watch list. I put just below the debug trace. 
This seems not to happen on every try. It may be linked with a QListWidgetItem on refreshing. 
I've tried to find out where this comes from without success. Do you have a clue @ochurlaud ? 

```
[MainWindow] In ToWatch detected
[MainWindow] Movie removed from playlist To Watch
[MainWindow] selfUpdate()
[MainWindow] Enters updatePannels()
[MainWindow] Enters fillMainPannel()
[MainWindow] mainPannel selected
[MainWindow] Enter fillMetadataPannel
[MainWindow] Exit fillMetadataPannel
[MainWindow] prepareMoviesToDisplay()
[MainWindow] Exits fillMainPannel()
[MainWindow] Enters fillLeftPannel()
[MainWindow] item seleceted on leftPannel
[MainWindow] item seleceted on leftPannel
[MainWindow] Enters fillMainPannel()
[MainWindow] prepareMoviesToDisplay()
[MainWindow] Exits fillMainPannel()
[MainWindow] Exits fillLeftPannel()
[MainWindow] Exits updatePannels()
[MainWindow] Enters fillMainPannel()
[MainWindow] prepareMoviesToDisplay()
[MainWindow] Exits fillMainPannel()
ASSERT failure in QList<T>::at: "index out of range", file /opt/Qt/5.3/gcc_64/include/QtCore/qlist.h, line 479
Le programme s'est terminé subitement.
```

**Comment by sebtouze** [comment]
The app sometimes crashes in similar way when trying to open a MovieMetadata
Maybe liked with #87

**Comment by ochurlaud** [comment]
Yes it means you try to access an item out of range... i'll check that in the week

**Comment by ochurlaud** [comment]
ok next week

**Comment by ochurlaud** [comment]
Both are linked... The problem is that if you select a movie, Macaw shows the metadata, then you remove it from the list and, after updating,  Macaw tries to access the metadata of the selected movie. Because it's not found, it crashes.
